"""Add agenda table

Revision ID: 7318b0978428
Revises: 
Create Date: 2025-10-01 01:06:18.896089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7318b0978428'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formularios_verificacao')
    op.drop_constraint(op.f('unique_resposta_pergunta'), 'checklist_respostas', type_='unique')
    op.drop_column('checklist_respostas', 'valor')
    op.alter_column('checklists_diarios', 'nota',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('formularios_meta_id_fkey'), 'formularios', type_='foreignkey')
    op.drop_column('formularios', 'meta_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formularios', sa.Column('meta_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('formularios_meta_id_fkey'), 'formularios', 'metas_terapeuticas', ['meta_id'], ['id'])
    op.alter_column('checklists_diarios', 'nota',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('checklist_respostas', sa.Column('valor', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('unique_resposta_pergunta'), 'checklist_respostas', ['checklist_id', 'pergunta_id'], postgresql_nulls_not_distinct=False)
    op.create_table('formularios_verificacao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['metas_terapeuticas.id'], name=op.f('formularios_verificacao_meta_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('formularios_verificacao_pkey'))
    )
    # ### end Alembic commands ###
